"""Add lookup tables for candidates

Revision ID: 1faaaf546bcb
Revises: f2e5013d256d
Create Date: 2025-09-10 12:20:20.593350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1faaaf546bcb'
down_revision = 'f2e5013d256d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_channels',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('candidate_statuses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('positions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('candidates', sa.Column('position_id', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('application_channel_id', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('status_id', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('hr_specialist_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'application_channels', ['application_channel_id'], ['id'])
    op.create_foreign_key(None, 'candidates', 'users', ['hr_specialist_id'], ['id'])
    op.create_foreign_key(None, 'candidates', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(None, 'candidates', 'candidate_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'hr_specialist_id')
    op.drop_column('candidates', 'status_id')
    op.drop_column('candidates', 'application_channel_id')
    op.drop_column('candidates', 'position_id')
    op.drop_table('positions')
    op.drop_table('candidate_statuses')
    op.drop_table('application_channels')
    # ### end Alembic commands ###









