"""Add cv_files table

Revision ID: 33637ab58cf6
Revises: 7048d6e1a4a0
Create Date: 2025-09-05 19:45:01.598327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33637ab58cf6'
down_revision = '7048d6e1a4a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


