"""Add cv_files table with constraints

Revision ID: 4f86a1f19c18
Revises: 33637ab58cf6
Create Date: 2025-09-05 19:45:59.489418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f86a1f19c18'
down_revision = '33637ab58cf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mime_type IN ('application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')", name='chk_mime_type_valid'),
    sa.CheckConstraint('LENGTH(filename) > 0', name='chk_filename_not_empty'),
    sa.CheckConstraint('LENGTH(original_filename) > 0', name='chk_original_filename_not_empty'),
    sa.CheckConstraint('file_size <= 10485760', name='chk_file_size_limit'),
    sa.CheckConstraint('file_size > 0', name='chk_file_size_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_files_is_active'), 'cv_files', ['is_active'], unique=False)
    op.create_index(op.f('ix_cv_files_user_id'), 'cv_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_files_user_id'), table_name='cv_files')
    op.drop_index(op.f('ix_cv_files_is_active'), table_name='cv_files')
    op.drop_table('cv_files')
    # ### end Alembic commands ###


