"""Add case study models

Revision ID: 545e2657d833
Revises: 8b3e52520c55
Create Date: 2025-09-11 11:38:06.259413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545e2657d833'
down_revision = '8b3e52520c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_study_statuses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('case_studies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('status_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['case_study_statuses.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_studies_due_date'), 'case_studies', ['due_date'], unique=False)
    op.create_index(op.f('ix_case_studies_id'), 'case_studies', ['id'], unique=False)
    op.create_index(op.f('ix_case_studies_is_active'), 'case_studies', ['is_active'], unique=False)
    op.create_index(op.f('ix_case_studies_status'), 'case_studies', ['status'], unique=False)
    op.create_index(op.f('ix_case_studies_title'), 'case_studies', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_studies_title'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_status'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_is_active'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_id'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_due_date'), table_name='case_studies')
    op.drop_table('case_studies')
    op.drop_table('case_study_statuses')
    # ### end Alembic commands ###









