"""Update user table for roles v3

Revision ID: 64d7f3ce3683
Revises: 907f4b55b36d
Create Date: 2025-09-11 15:06:38.675454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d7f3ce3683'
down_revision = '907f4b55b36d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'user_roles', ['role_id'], ['id'])
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###









