"""update_candidate_status_constraint

Revision ID: 8b3e52520c55
Revises: de21c08dc6eb
Create Date: 2025-09-10 14:12:48.723087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3e52520c55'
down_revision = 'de21c08dc6eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###









