"""Add candidates table

Revision ID: 8c8f2e2afd56
Revises: c8b42a5a1e44
Create Date: 2025-09-09 13:19:32.616039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8f2e2afd56'
down_revision = 'c8b42a5a1e44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('application_channel', sa.String(length=50), nullable=False),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hr_specialist', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cv_file_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("application_channel IN ('LinkedIn', 'Kariyer.net', 'Referanslı', 'İş Görüşmesi', 'Diğer')", name='chk_application_channel_valid'),
    sa.CheckConstraint("status IN ('Başvurdu', 'İnceleme', 'Mülakat', 'Teklif', 'İşe Alındı', 'Reddedildi')", name='chk_status_valid'),
    sa.CheckConstraint('LENGTH(application_channel) > 0', name='chk_application_channel_not_empty'),
    sa.CheckConstraint('LENGTH(email) > 0', name='chk_email_not_empty'),
    sa.CheckConstraint('LENGTH(first_name) > 0', name='chk_first_name_not_empty'),
    sa.CheckConstraint('LENGTH(hr_specialist) > 0', name='chk_hr_specialist_not_empty'),
    sa.CheckConstraint('LENGTH(last_name) > 0', name='chk_last_name_not_empty'),
    sa.CheckConstraint('LENGTH(phone) > 0', name='chk_phone_not_empty'),
    sa.CheckConstraint('LENGTH(position) > 0', name='chk_position_not_empty'),
    sa.CheckConstraint('LENGTH(status) > 0', name='chk_status_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_application_date'), 'candidates', ['application_date'], unique=False)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_index(op.f('ix_candidates_first_name'), 'candidates', ['first_name'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_is_active'), 'candidates', ['is_active'], unique=False)
    op.create_index(op.f('ix_candidates_last_name'), 'candidates', ['last_name'], unique=False)
    op.create_index(op.f('ix_candidates_position'), 'candidates', ['position'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_position'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_last_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_is_active'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_first_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_application_date'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###








