"""Add foreign key columns to candidates table

Revision ID: f2e5013d256d
Revises: 8c8f2e2afd56
Create Date: 2025-09-09 14:16:25.312285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e5013d256d'
down_revision = '8c8f2e2afd56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('candidate_statuses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('candidates_application_channel_id_fkey', 'candidates', type_='foreignkey')
    op.drop_constraint('candidates_position_id_fkey', 'candidates', type_='foreignkey')
    op.drop_constraint('candidates_status_id_fkey', 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'position_id')
    op.drop_column('candidates', 'application_channel_id')
    op.drop_column('candidates', 'status_id')
    op.alter_column('positions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('candidates', sa.Column('status_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('application_channel_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('position_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('candidates_status_id_fkey', 'candidates', 'candidate_statuses', ['status_id'], ['id'])
    op.create_foreign_key('candidates_position_id_fkey', 'candidates', 'positions', ['position_id'], ['id'])
    op.create_foreign_key('candidates_application_channel_id_fkey', 'candidates', 'application_channels', ['application_channel_id'], ['id'])
    op.alter_column('candidate_statuses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('application_channels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###








